catalog/urls.py
from django.urls import path
from . import views

# URL pattern is an empty string
# view function that will be called if the URL pattern is detected : views.index()
urlpatterns = [
    path('', views.index, name='index'),
    # as_view() function used to create an instance of the class
    path('books/', views.BookListView.as_view(), name='books'), 
    # <> define the part of the URL to be captured, enclosing the name of the variable
    # that the view can use to access the captured data
    # <something> capture the pattern and pass the value to the view as a variable something
    # can precede the variable name with a converter specification like int, str, path
    # pk (short for primary key) - id that is being used to store the book uniquely
    path('book/<int:pk>', views.BookDetailView.as_view(), name ='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed', views.AllLoanedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name = 'renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
# includes a path() that forwards requests with the pattern
# catalog/ to the module catalogs.urls
from django.urls import include

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView

# The first patameter of the path function empty to imply '/'
urlpatterns += [
    path ('', RedirectView.as_view(url='catalog/', permanent = True)),
]

# Use static() to add url mapping to server static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path ('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User #used to import the user model
from datetime import date

# Create your models here.
# Genre Model
class Genre (models.Model):
    """Model representing a book genre."""
    # ---- Fields ----    
    name = models.CharField(max_length=200, help_text = 'Enter a book genre (e.g. Science Fiction)')

    # ---- Methods ----
    def __str__ (self):
        """String for representing the Model object."""
        # Returns the name of the genre
        return self.name

class Language (models.Model):
    """Model representing a language"""
    # ---- Fields ----
    name = models.CharField(max_length=200, help_text = 'Enter a language for the book (e.g. French)')

    # ---- Methods ----
    def __str__ (self):
        return self.name

# Book Model
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)"""
    # ---- Fields ----
    title = models.CharField(max_length=200, help_text = "Title of the book")
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    # null = True -> allows database to store a null value if no author is selected
    # on_delete -> set the value of author to NULL if the associated author record is deleted
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null = True)
    summary = models.TextField(max_length=1000, help_text = 'Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null = True)
    
    # ---- Methods ----
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    # Returns a URL that can be used to access a detail record for this model
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin.
            Only shows the first three values of genre."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'
class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    # ---- Fields ----
    # UUIDField used to set id as primary key - Allocates a global unique value for each instance
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, help_text = "Publishing Company")
    due_back = models.DateField(null=True, blank=True, help_text = 'The date the book is due')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    # Key-pair values - Value is a display value the user can select
    # Keys are the values that are actually saved if it selected
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length = 1,
        choices = LOAN_STATUS,
        blank = True,
        default = 'm',
        help_text = 'Book availability',
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    # Will be sorted alphabetically by due_back
    class Meta:
        ordering = ['due_back']
        permissions = (("catalog.can_mark_returned", "Can edit the book"),)

    # ---- Methods ----
    def __str__ (self):
        """String for representing the Model Object."""
        return f'{self.id} ({self.book.title})'

class Author (models.Model):
    """Model representing an author."""
    # --- Fields ---
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null = True, blank = True)

    # Will be sorted alphabetically by last name and then first name
    class Meta:
        ordering = ['last_name', 'first_name']

    # ---- Methods ----
    # reverses the author-detail URL mapping to get the URL for displaying an individual author
    def get_absolute_url (self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__ (self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text = "Enter a date between now and 4 weeks (default 3).")

    # Used to validate a single field, overrides the method clean_<fieldname>()
    def clean_renewal_date(self):
        # Gets the data "cleaned" and converted to correct standard type
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past
        if data < datetime.date.today():
            # (_ ()) in case to translate the site later
            raise ValidationError(_('Invalid date - renewal in the past'))

        # Check if a date is in the allowed range (+4 weeks from today)
        if data > datetime.date.today():
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data
        return data

catalog/views.py
from django.shortcuts import render
# import the model classes in order to access the data
from catalog.models import Book, Author, BookInstance, Genre
# import the generic list view
from django.views import generic

# Create your views here.
# Used to process an HTTP request, fetch data from the database, and render
# the data in an HTML page


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_authors = Author.objects.count()
    num_books_game = Book.objects.filter(title__contains='game').count()
    num_genres = Genre.objects.all().count()

    # Number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 0) # Sets to 0 if not previously been set
    # Each time a request is received, increment the value and store it back in session
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_books_game': num_books_game,
        'num_genres': num_genres,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    # request - HttpRequest, index.html --> html template wtih placeholders for the data
    # index.html expected to be found in catalog/templates/
    # context - python dictionary containing the data to insert into the placeholders
    return render(request, 'index.html', context=context)

# use a class-based generic list view (ListView) - a class that inherits from an existing view
class BookListView(generic.ListView):
    """The generic view will query the database to get all records for the
    specific model (Book) and render a template"""
    model = Book
    # your own name for the list as a template variable
    #context_object_name = 'my_book_list'
    # Get 5 books containing the title
    #queryset = Book.objects.filter(title__icontains='silent')[:5]
    # Adds pagination to the list views, reducing number of items displayed on each page
    paginate_by = 4
    
class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4

class AuthorDetailView(generic.DetailView):
    model = Author

# Used to add the view of list of books loaned to the current user
# This import allows only the logged in user to call this view
from django.contrib.auth.mixins import LoginRequiredMixin
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    # May have different lists of BookInstance records with different views and templates
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    # Restrict query to just BookInstance objects for the current user
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back') 

# Used to add the view of list of all books loaned
# Allows only those with permission to call this view
from django.contrib.auth.mixins import PermissionRequiredMixin
class AllLoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    """"Generic class-based view listing all books on loan. Can only be viewed
    with the can_edit permission """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_all_borrowed.html'
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

# The view for the form when a librarian is renewing a book
import datetime
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404 # Raises exception if the record isn't found
from django.http import HttpResponseRedirect # Creates redirect to a specified URL
from django.urls import reverse

# from .forms import RenewBookForm
from catalog.forms import RenewBookForm

# Function decorator
@permission_required('catalog.can_mark_returned')
# pk argument in get_object_or_404() to get the current BookSInstance
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    # Contains our BookInstance
    context = {
        'form': form,
        'book_instance': book_instance,
    }
    
    # Render creates the HTML page
    return render(request, 'catalog/book_renew_librarian.html', context)

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Author

# Need to derive from CreateView in order to create, update, or delete the view
class AuthorCreate(CreateView):
    model = Author
    # Used to specify the fields to display in the form
    fields = '__all__'
    # Specifies initial values for each of the fields
    initial = {'date_of_death': '05/01/2018'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    # Redirects to the author list after an author has been deleated
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author }}</h1>

  <p><strong>Date of Birth:</strong> <a href="">{{ author.date_of_birth }}</a></p>
  <p><strong>Date of Death:</strong> {{ author.date_of_death }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <p>{{book.summary}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    <!-- Used to ensure our forms are resistant to CSRF attacks-->
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <!--Creates a list item for each author and shows the name (as link) and author
        use dot notation to access the fields of associated book record. book.get_absolute_url
         grabs the URL to display the associated detail record-->
        <a href="{{ author.get_absolute_url }}">{{ author }}</a> ({{author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>
    <!-- book.bookinstance_set.all() returns the set of BookInstance records with a particular book-->
    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <!--Creates a list item for each book and shows the title (as link) and author
        use dot notation to access the fields of associated book record. book.get_absolute_url
         grabs the URL to disply the associated detail record-->
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
  <!--Empty form action causes the form data to be posted back to the current URL-->  
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_all_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
        {% if user.is_staff %} - {{bookinst.borrower}} {% endif %}
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  
        {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}